version: '3.3'
services:

  db:
    image: postgres:13-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
      
  backend:
    image: greengnom1/foodgram_backend:latest
    expose:
      - 8000
    restart: always
    volumes:
      - static_value: /app/static/
      - media_value: /app/media/
    depend_on:
      - db
    env_file:
      - ./.env
      
  nginx:
    image: nginx:1.19.3
    ports: "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/static/
      - media_value:/app/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - backend
      - fronted

  frontend:
    image: greengnom1/foodgram_fronted:v13.07.2022
    ports:
      - "80:80"
    volumes:
      - ..fronted/:/app/result_build/
      
  volumes:
    postgres_data:
    static_value:
    media_value:
