# Generated by Django 2.2.16 on 2022-06-26 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220622_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Изображение люда'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]+$', 'Символы латинского алфавита, цифры и знак подчёркивания')]),
        ),
    ]
