# Generated by Django 2.2.16 on 2022-08-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220803_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/recipes/', verbose_name='Изображение блюда'),
        ),
    ]
