# Generated by Django 2.2.16 on 2022-08-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220804_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(default=8, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
