# Generated by Django 2.2.16 on 2022-08-09 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220809_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Количество продукта не может быть ниже 1')], verbose_name='Количество ингредиентов'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(help_text='Напишите время готовки в минутах', validators=[django.core.validators.MinValueValidator(1, message='Время готовки не должно быть ниже 1')], verbose_name='Время готовки'),
        ),
    ]
