# Generated by Django 2.2.16 on 2022-07-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20220709_1413'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique cart user',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique cart'),
        ),
    ]
